# Generated by Django 4.2.16 on 2025-03-10 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocha', '0002_alter_item_created_at_alter_item_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Store1Item',
        ),
        migrations.CreateModel(
            name='Store2Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField()),
                ('code', models.CharField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('retail_price', models.CharField(blank=True)),
                ('stock', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_visible', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocha.category')),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ocha.subcategory')),
            ],
        ),
    ]
