# Generated by Django 4.2.16 on 2025-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocha', '0004_ochastore1item_ochastore2item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ochastore1item',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ochastore1item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ochastore1item',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ochastore2item',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ochastore2item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ochastore2item',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
