# Generated by Django 4.2.16 on 2025-02-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='maker_code',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='maker_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='margin_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.margin'),
        ),
    ]
