# Generated by Django 4.2.16 on 2025-02-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_margin_item_maker_code_item_maker_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='margin',
            name='group_name',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='margin',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='maker_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
