# Generated by Django 4.2.16 on 2025-03-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_is_alive_item_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postage', models.CharField(null=True)),
                ('supplier', models.CharField(null=True)),
                ('classification', models.CharField(null=True)),
                ('maker', models.CharField(null=True)),
                ('category', models.CharField(null=True)),
            ],
        ),
    ]
