# Generated by Django 4.2.16 on 2025-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='classification',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='maker',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='postage',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(null=True),
        ),
    ]
