# Generated by Django 4.2.16 on 2025-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bargain_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='classification',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='jan_code',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='maker',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='postage',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_code',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='margin',
            name='group_name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='margin',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
