# Generated by Django 4.2.16 on 2025-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_category_classification_maker_postage_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bargain_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='list_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_count',
            field=models.IntegerField(blank=True),
        ),
    ]
