# Generated by Django 4.2.16 on 2025-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_bargain_price_alter_item_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bargain_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='jan_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock_count',
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.CharField(),
        ),
    ]
