# Generated by Django 4.2.16 on 2025-03-10 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakakucom', '0002_alter_item_created_at_alter_item_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Store1Item',
        ),
        migrations.CreateModel(
            name='Store2Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(blank=True)),
                ('code', models.CharField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('store', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('comment', models.CharField(blank=True)),
                ('warranty', models.BooleanField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.category')),
                ('delivery_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.deliverygroup')),
                ('maker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.maker')),
                ('stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.stock')),
            ],
        ),
    ]
