# Generated by Django 4.2.16 on 2025-03-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_updated_at'),
        ('kakakucom', '0003_rename_item_store1item_store2item'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakakuStore1Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(blank=True)),
                ('code', models.CharField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('store', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('comment', models.CharField(blank=True)),
                ('warranty', models.BooleanField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.category')),
                ('delivery_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.deliverygroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('maker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.maker')),
                ('stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.stock')),
            ],
        ),
        migrations.CreateModel(
            name='KakakuStore2Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(blank=True)),
                ('code', models.CharField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('store', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('comment', models.CharField(blank=True)),
                ('warranty', models.BooleanField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.category')),
                ('delivery_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.deliverygroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('maker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.maker')),
                ('stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kakakucom.stock')),
            ],
        ),
        migrations.RemoveField(
            model_name='store2item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='store2item',
            name='delivery_group',
        ),
        migrations.RemoveField(
            model_name='store2item',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='store2item',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Store1Item',
        ),
        migrations.DeleteModel(
            name='Store2Item',
        ),
    ]
