# Generated by Django 4.2.16 on 2025-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakakucom', '0004_kakakustore1item_kakakustore2item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakakustore1item',
            name='delivery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kakakustore1item',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='kakakustore2item',
            name='delivery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kakakustore2item',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
