# Generated by Django 5.1.1 on 2024-09-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rakuten.item'),
            preserve_default=False,
        ),
    ]
