# Generated by Django 5.1.1 on 2024-09-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0002_sku_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hide_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='hidden',
            field=models.IntegerField(default=0),
        ),
    ]
