# Generated by Django 5.1.1 on 2024-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0003_remove_item_hide_item_remove_item_manage_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='precautions_agreement',
        ),
        migrations.RemoveField(
            model_name='item',
            name='precautions_description',
        ),
        migrations.AlterField(
            model_name='item',
            name='tagline',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='hidden',
            field=models.BooleanField(null=True),
        ),
    ]
