# Generated by Django 5.1.1 on 2024-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0004_remove_item_precautions_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images_alt',
        ),
        migrations.RemoveField(
            model_name='item',
            name='images_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='images_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='video_parameters_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='video_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='whiteBgImage_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='whiteBgImage_type',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(null=True),
        ),
    ]
