# Generated by Django 5.1.1 on 2024-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0005_remove_item_images_alt_remove_item_images_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
