# Generated by Django 5.1.1 on 2024-10-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0006_sku_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='skuNumber',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
