# Generated by Django 5.1.1 on 2024-10-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0007_alter_sku_skunumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
