# Generated by Django 4.2.16 on 2024-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0009_item_accesscontrol_accesspassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='features_displayNormalCartButton',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_displaySubscriptionCartButton',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_shopContact',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='hideItem',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='payment_cashOnDeliveryFeeIncluded',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='payment_taxIncluded',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subscription_shippingDateFlag',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subscription_shippingIntervalFlag',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unlimitedInventoryFlag',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='hidden',
            field=models.CharField(null=True),
        ),
    ]
