# Generated by Django 4.2.16 on 2024-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0010_alter_item_features_displaynormalcartbutton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pointCampaign_applicablePeriod_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pointCampaign_applicablePeriod_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchasablePeriod_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchasablePeriod_start',
            field=models.DateTimeField(null=True),
        ),
    ]
