# Generated by Django 4.2.16 on 2024-11-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0011_alter_item_pointcampaign_applicableperiod_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='controlColumn',
            field=models.CharField(null=True),
        ),
    ]
