# Generated by Django 4.2.16 on 2024-12-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0013_item_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
