# Generated by Django 4.2.16 on 2024-12-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0014_alter_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
