# Generated by Django 4.2.16 on 2025-02-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_margin_group_name_margin_rate_alter_item_maker_price'),
        ('rakuten', '0015_sku_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
