# Generated by Django 4.2.16 on 2025-03-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_updated_at'),
        ('rakuten', '0017_remove_item_accesscontrol_accesspassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordiroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manageNumber', models.CharField()),
                ('itemNumber', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField()),
                ('tagline', models.CharField(blank=True)),
                ('productDescription_pc', models.TextField(blank=True)),
                ('productDescription_sp', models.TextField(blank=True)),
                ('salesDescription', models.TextField(blank=True)),
                ('precautions', models.JSONField(blank=True, null=True)),
                ('itemType', models.CharField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('whiteBgImage', models.JSONField(blank=True, null=True)),
                ('video', models.JSONField(blank=True, null=True)),
                ('genreId', models.CharField()),
                ('tags', models.JSONField(blank=True, null=True)),
                ('hideItem', models.CharField()),
                ('unlimitedInventoryFlag', models.CharField()),
                ('customizationOptions', models.JSONField(blank=True, null=True)),
                ('releaseDate', models.DateField(blank=True)),
                ('purchasablePeriod', models.JSONField(blank=True, null=True)),
                ('subscription', models.JSONField(blank=True, null=True)),
                ('features', models.JSONField(null=True)),
                ('accessControl', models.JSONField(blank=True, null=True)),
                ('payment', models.JSONField(null=True)),
                ('pointCampaign', models.JSONField(blank=True, null=True)),
                ('itemDisplaySequence', models.IntegerField()),
                ('layout', models.JSONField(null=True)),
                ('variantSelectors', models.JSONField(blank=True, null=True)),
                ('created', models.DateField(null=True)),
                ('updated', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='MaidoItem',
        ),
        migrations.RenameModel(
            old_name='Sku',
            new_name='MaidoSku',
        ),
        migrations.CreateModel(
            name='CoordiroomSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variantId', models.CharField(blank=True, db_index=True, max_length=255)),
                ('merchantDefinedSkuId', models.CharField(blank=True)),
                ('selectorValues', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('restockOnCancel', models.CharField(blank=True)),
                ('backOrderFlag', models.CharField(blank=True)),
                ('normalDeliveryDateId', models.IntegerField(blank=True)),
                ('backOrderDeliveryDateId', models.IntegerField(blank=True)),
                ('orderQuantityLimit', models.IntegerField(blank=True)),
                ('referencePrice', models.JSONField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('hidden', models.CharField(blank=True)),
                ('standardPrice', models.IntegerField(blank=True)),
                ('subscriptionPrice', models.JSONField(blank=True, null=True)),
                ('articleNumberForSet', models.JSONField(blank=True, null=True)),
                ('articleNumber', models.JSONField(blank=True, null=True)),
                ('shipping', models.JSONField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rakuten.coordiroomitem')),
            ],
        ),
    ]
