# Generated by Django 4.2.16 on 2025-03-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_updated_at'),
        ('rakuten', '0018_coordiroomitem_rename_item_maidoitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoordiroomItem',
            new_name='RakutenCoordiroomItem',
        ),
        migrations.RenameModel(
            old_name='CoordiroomSku',
            new_name='RakutenCoordiroomSku',
        ),
        migrations.RenameModel(
            old_name='MaidoItem',
            new_name='RakutenMaidoItem',
        ),
        migrations.RenameModel(
            old_name='MaidoSku',
            new_name='RakutenMaidoSku',
        ),
    ]
