# Generated by Django 4.2.16 on 2025-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0021_remove_rakutencoordiroomitem_productdescription_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='accessControl',
            field=models.JSONField(default={'cashOnDeliveryFeeIncluded': '代引料', 'taxIncluded': '消費税込み', 'taxRate': '消費税税率'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='customizationOptions',
            field=models.JSONField(default={'customizationOptions': [{'displayName': '商品オプション（項目選択肢）項目名', 'inputType': '商品オプション選択肢タイプ', 'required': '商品オプション必須フラグ', 'selections': [{'displayValue': '商品オプション選択肢名'}]}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='features',
            field=models.JSONField(default={'displayManufacturerContents': 'メーカー提供情報表示', 'displayNormalCartButton': '注文ボタン', 'displaySubscriptionCartButton': '定期購入ボタン', 'inventoryDisplay': '在庫数表示', 'lowStockThreshold': '残り在庫数表示閾値', 'review': 'レビュー本文表示', 'searchVisiblity': 'サーチ表示', 'shopContact': '商品問い合わせボタン'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='hideItem',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='images',
            field=models.JSONField(default={'images': [{'alt': '商品画像名（ALT）', 'location': '商品画像種別', 'type': '商品画像種別'}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='layout',
            field=models.JSONField(default={'itemLayoutId': '\t商品ページレイアウト', 'largeDescriptionId': '共通説明文(大)テンプレートID', 'layoutSequenceId': '表示項目の並び順テンプレートID', 'navigationId': 'ヘッダー・フッター・レフトナビのテンプレートID', 'showcaseId': '目玉商品テンプレートID', 'smallDescriptionId': '共通説明文(小)テンプレートID'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='payment',
            field=models.JSONField(default={'cashOnDeliveryFeeIncluded': '代引料', 'taxIncluded': '消費税込み', 'taxRate': '消費税税率'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='pointCampaign',
            field=models.JSONField(default={'applicablePeriod': {'end': '終了日時', 'start': '開始日時'}, 'benefits': {'pointRate': 'ポイント変倍率'}, 'optimization': {'maxPointRate': 'ポイント上限倍率'}}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='precautions',
            field=models.JSONField(default={'agreement': '医療品注意事項', 'description': '医薬品説明文'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='productDescription',
            field=models.JSONField(default={'pc': 'PC要商品説明文', 'sp': 'スマートフォン要商品説明文'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='purchasablePeriod',
            field=models.JSONField(default={'end': '販売終了日時', 'start': '販売開始日時'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='subscription',
            field=models.JSONField(default={'shippingDateFlag': 'お届け日付指定フラグ', 'shippingIntervalFlag': 'お届け間隔指定フラグ'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='tags',
            field=models.JSONField(default={'tags': []}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='variantSelectors',
            field=models.JSONField(default={'displayName': 'バリエーション項目名', 'key': 'バリエーション項目キー', 'values': [{'displayValue': 'バリエーション選択肢'}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='video',
            field=models.JSONField(default={'parameters': {'value': '動画のURL'}, 'type': '動画種別'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='whiteBgImage',
            field=models.JSONField(default={'location': '白背景画像URL', 'type': '白背景画像種別'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='accessControl',
            field=models.JSONField(default={'cashOnDeliveryFeeIncluded': '代引料', 'taxIncluded': '消費税込み', 'taxRate': '消費税税率'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='features',
            field=models.JSONField(default={'displayManufacturerContents': 'メーカー提供情報表示', 'displayNormalCartButton': '注文ボタン', 'displaySubscriptionCartButton': '定期購入ボタン', 'inventoryDisplay': '在庫数表示', 'lowStockThreshold': '残り在庫数表示閾値', 'review': 'レビュー本文表示', 'searchVisiblity': 'サーチ表示', 'shopContact': '商品問い合わせボタン'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='layout',
            field=models.JSONField(default={'itemLayoutId': '\t商品ページレイアウト', 'largeDescriptionId': '共通説明文(大)テンプレートID', 'layoutSequenceId': '表示項目の並び順テンプレートID', 'navigationId': 'ヘッダー・フッター・レフトナビのテンプレートID', 'showcaseId': '目玉商品テンプレートID', 'smallDescriptionId': '共通説明文(小)テンプレートID'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='payment',
            field=models.JSONField(default={'cashOnDeliveryFeeIncluded': '代引料', 'taxIncluded': '消費税込み', 'taxRate': '消費税税率'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='pointCampaign',
            field=models.JSONField(default={'applicablePeriod': {'end': '終了日時', 'start': '開始日時'}, 'benefits': {'pointRate': 'ポイント変倍率'}, 'optimization': {'maxPointRate': 'ポイント上限倍率'}}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='purchasablePeriod',
            field=models.JSONField(default={'end': '販売終了日時', 'start': '販売開始日時'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='subscription',
            field=models.JSONField(default={'shippingDateFlag': 'お届け日付指定フラグ', 'shippingIntervalFlag': 'お届け間隔指定フラグ'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='variantSelectors',
            field=models.JSONField(default={'displayName': 'バリエーション項目名', 'key': 'バリエーション項目キー', 'values': [{'displayValue': 'バリエーション選択肢'}]}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='articleNumber',
            field=models.JSONField(default={'exemptionReason': 'カタログIDなしの理由', 'value': 'カタログID'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='attributes',
            field=models.JSONField(default={'attributes': [{'name': '属性情報名', 'unit': '単位', 'values': '\t属性情報（実値）'}]}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='features',
            field=models.JSONField(default={'noshi': 'のし対応', 'restockNotification': '再入荷お知らせボタン'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='images',
            field=models.JSONField(default={'images': [{'alt': 'SKU画像名（ALT）', 'location': '\tSKU画像パス', 'type': 'SKU画像タイプ'}]}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='referencePrice',
            field=models.JSONField(default={'displayType': '表示価格種別', 'type': '表示価格文言', 'value': '表示価格'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='selectorValues',
            field=models.JSONField(default={'key': None}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='shipping',
            field=models.JSONField(default={'fee': '個別送料', 'overseasDeliveryId': '海外配送管理番号', 'postageIncluded': '送料無料フラグ', 'postageSegment': {'local': '\t送料区分1（ローカル）', 'overseas': '送料区分2（海外）'}, 'shippingMethodGroup': '配送方法セット管理番号', 'shopAreaSoryoPatternId': '地域別個別送料管理番号', 'singleItemShipping': '単品配送設定'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='specs',
            field=models.JSONField(default={'specs': [{'label': '属性情報自由入力行（項目）', 'value': '属性情報自由入力行（値）'}]}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='subscriptionPrice',
            field=models.JSONField(default={'basePrice': '定期購入販売価格', 'individualPrices': {'firstPrice': '初回価格'}}),
        ),
    ]
