# Generated by Django 4.2.16 on 2025-03-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0022_alter_rakutencoordiroomitem_accesscontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='articleNumber',
            field=models.JSONField(default={'exemptionReason': 'カタログIDなしの理由', 'value': 'カタログID'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='attributes',
            field=models.JSONField(default={'attributes': [{'name': '属性情報名', 'unit': '単位', 'values': '\t属性情報（実値）'}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='features',
            field=models.JSONField(default={'noshi': 'のし対応', 'restockNotification': '再入荷お知らせボタン'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='images',
            field=models.JSONField(default={'images': [{'alt': 'SKU画像名（ALT）', 'location': '\tSKU画像パス', 'type': 'SKU画像タイプ'}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rakuten.rakutenmaidoitem'),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='referencePrice',
            field=models.JSONField(default={'displayType': '表示価格種別', 'type': '表示価格文言', 'value': '表示価格'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='selectorValues',
            field=models.JSONField(default={'key': None}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='shipping',
            field=models.JSONField(default={'fee': '個別送料', 'overseasDeliveryId': '海外配送管理番号', 'postageIncluded': '送料無料フラグ', 'postageSegment': {'local': '\t送料区分1（ローカル）', 'overseas': '送料区分2（海外）'}, 'shippingMethodGroup': '配送方法セット管理番号', 'shopAreaSoryoPatternId': '地域別個別送料管理番号', 'singleItemShipping': '単品配送設定'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='specs',
            field=models.JSONField(default={'specs': [{'label': '属性情報自由入力行（項目）', 'value': '属性情報自由入力行（値）'}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='subscriptionPrice',
            field=models.JSONField(default={'basePrice': '定期購入販売価格', 'individualPrices': {'firstPrice': '初回価格'}}),
        ),
    ]
