# Generated by Django 4.2.16 on 2025-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0023_alter_rakutencoordiroomsku_articlenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='attributes',
            field=models.JSONField(default={'attributes': [{'name': '属性情報名', 'unit': '単位', 'values': '属性情報（実値）'}]}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='shipping',
            field=models.JSONField(default={'fee': '個別送料', 'overseasDeliveryId': '海外配送管理番号', 'postageIncluded': '送料無料フラグ', 'postageSegment': {'local': '送料区分1（ローカル）', 'overseas': '送料区分2（海外）'}, 'shippingMethodGroup': '配送方法セット管理番号', 'shopAreaSoryoPatternId': '地域別個別送料管理番号', 'singleItemShipping': '単品配送設定'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='attributes',
            field=models.JSONField(default={'attributes': [{'name': '属性情報名', 'unit': '単位', 'values': '属性情報（実値）'}]}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='shipping',
            field=models.JSONField(default={'fee': '個別送料', 'overseasDeliveryId': '海外配送管理番号', 'postageIncluded': '送料無料フラグ', 'postageSegment': {'local': '送料区分1（ローカル）', 'overseas': '送料区分2（海外）'}, 'shippingMethodGroup': '配送方法セット管理番号', 'shopAreaSoryoPatternId': '地域別個別送料管理番号', 'singleItemShipping': '単品配送設定'}),
        ),
    ]
