# Generated by Django 4.2.16 on 2025-03-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0025_alter_rakutencoordiroomitem_hideitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='unlimitedInventoryFlag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='unlimitedInventoryFlag',
            field=models.BooleanField(),
        ),
    ]
