# Generated by Django 4.2.16 on 2025-03-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0026_alter_rakutencoordiroomitem_unlimitedinventoryflag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakutencoordiroomitem',
            name='layout',
            field=models.JSONField(default={'itemLayoutId': '商品ページレイアウト', 'largeDescriptionId': '共通説明文(大)テンプレートID', 'layoutSequenceId': '表示項目の並び順テンプレートID', 'navigationId': 'ヘッダー・フッター・レフトナビのテンプレートID', 'showcaseId': '目玉商品テンプレートID', 'smallDescriptionId': '共通説明文(小)テンプレートID'}),
        ),
        migrations.AlterField(
            model_name='rakutencoordiroomsku',
            name='images',
            field=models.JSONField(default={'images': [{'alt': 'SKU画像名（ALT）', 'location': 'SKU画像パス', 'type': 'SKU画像タイプ'}]}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='layout',
            field=models.JSONField(default={'itemLayoutId': '商品ページレイアウト', 'largeDescriptionId': '共通説明文(大)テンプレートID', 'layoutSequenceId': '表示項目の並び順テンプレートID', 'navigationId': 'ヘッダー・フッター・レフトナビのテンプレートID', 'showcaseId': '目玉商品テンプレートID', 'smallDescriptionId': '共通説明文(小)テンプレートID'}),
        ),
        migrations.AlterField(
            model_name='rakutenmaidosku',
            name='images',
            field=models.JSONField(default={'images': [{'alt': 'SKU画像名（ALT）', 'location': 'SKU画像パス', 'type': 'SKU画像タイプ'}]}),
        ),
    ]
