# Generated by Django 4.2.16 on 2025-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0027_alter_rakutencoordiroomitem_layout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakutenmaidoitem',
            name='itemType',
            field=models.CharField(choices=[('NORMAL', '通常商品'), ('PRE_ORDER', '予約商品'), ('SUBSCRIPTION', '定期購入商品')]),
        ),
    ]
