# Generated by Django 4.2.16 on 2025-03-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0030_item_record_sku_remove_rakutencoordiroomsku_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='features',
        ),
        migrations.RemoveField(
            model_name='item',
            name='genreId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hideItem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemDisplaySequence',
        ),
        migrations.RemoveField(
            model_name='item',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='item',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unlimitedInventoryFlag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='is_deleted',
        ),
    ]
