# Generated by Django 4.2.16 on 2025-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuten', '0032_remove_item_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='our_price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
