# Generated by Django 4.2.16 on 2025-03-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField()),
                ('name', models.CharField()),
                ('code', models.CharField()),
                ('sub_code', models.CharField(blank=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('options', models.TextField(blank=True)),
                ('ship_weight', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('display', models.BooleanField(default=False)),
                ('delivery', models.CharField(blank=True)),
                ('product_category', models.CharField(blank=True)),
                ('spec1', models.CharField(blank=True)),
                ('spec2', models.CharField(blank=True)),
                ('spec3', models.CharField(blank=True)),
                ('spec4', models.CharField(blank=True)),
                ('spec5', models.CharField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
