# Generated by Django 4.2.16 on 2025-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_category',
            field=models.CharField(),
        ),
    ]
