# Generated by Django 4.2.16 on 2025-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_margin_group_name_margin_rate_alter_item_maker_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='maker_price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='maker_code',
            new_name='model_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='margin_rate',
        ),
        migrations.AddField(
            model_name='item',
            name='bargain_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='jan_code',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='list_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_code',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_count',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
