# Generated by Django 4.2.16 on 2025-02-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_item_code_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_alive',
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
