# Generated by Django 4.2.16 on 2025-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0006_yahoocoordiroomitem_yahoomaidoitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoocoordiroomitem',
            name='original_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahoocoordiroomitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yahoocoordiroomitem',
            name='sale_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahoocoordiroomitem',
            name='ship_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahoomaidoitem',
            name='original_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahoomaidoitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yahoomaidoitem',
            name='sale_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahoomaidoitem',
            name='ship_weight',
            field=models.IntegerField(blank=True),
        ),
    ]
