# Generated by Django 4.2.16 on 2025-03-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0007_alter_yahoocoordiroomitem_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='display',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='options',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='ship_weight',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='spec1',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='spec2',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='spec3',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='spec4',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='spec5',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='sub_code',
        ),
    ]
