# Generated by Django 4.2.16 on 2025-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0009_remove_yahoocoordiroomitem_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoocoordiroomitem',
            name='product_category',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahoomaidoitem',
            name='product_category',
            field=models.CharField(blank=True),
        ),
    ]
