# Generated by Django 4.2.16 on 2025-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0010_alter_yahoocoordiroomitem_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoocoordiroomitem',
            name='code',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='yahoomaidoitem',
            name='code',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='yahoomaidoitem',
            name='product_category',
            field=models.CharField(),
        ),
    ]
