# Generated by Django 4.2.16 on 2025-03-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0011_yahoocoordiroomitem_code_yahoomaidoitem_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahoocoordiroomitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='yahoomaidoitem',
            name='code',
        ),
    ]
