# Generated by Django 4.2.16 on 2025-03-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0014_remove_yahoocoordiroomitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoocoordiroomitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
